name: docker-build

on:
  push:
    branches: [ master ]

jobs:
  docker:
    name: Build and push docker image
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        if: success()
        uses: actions/checkout@v2
        
      - name: Prepare
        id: prepare
        run: |
          echo ::set-output name=docker_platforms::linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64
          echo ::set-output name=docker_image::linksmart/hds-datasync
          echo ::set-output name=version::${GITHUB_REF##*/}
          
      - name: Set up Docker Buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          buildx-version: latest
        
      - name: Docker login
        if: success()
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USER }}" --password-stdin

      - name: Docker Buildx (push) latest on master
        run: |
          docker buildx build --platform ${{ steps.prepare.outputs.docker_platforms }} \
            --output "type=image,push=true" \
            --tag "${{ steps.prepare.outputs.docker_image }}:latest" \
            --file Dockerfile .
